name: Build and Test the Skeleton app
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Gradle
        env:
          ARTIFACTORY_USERNAME2: ${{ secrets.ARTIFACTORY_USERNAME2 }}
          ARTIFACTORY_EDGE_PASSWORD2: ${{ secrets.ARTIFACTORY_EDGE_PASSWORD2 }}
          GRADLE_OPTS: "-Dgradle.wrapperUser=${{secrets.ARTIFACTORY_USERNAME2}} -Dgradle.wrapperPassword=${{secrets.ARTIFACTORY_EDGE_PASSWORD2}}"
        run: ./gradlew build --info